version: '3.6'

services:
  main:
    build: ./
    command: python3 main_vedomosti.py
#  redis:
#    image: redis:alpine
#  celery:
#    build: ./
#    command: celery -A core worker --loglevel=INFO --concurrency=10
#    depends_on:
#      - redis
#  celery-beat:
#    build: ./
#    command: celery -A core beat -l info
#    depends_on:
#      - redis