version: '3.6'

services:
#  main_news:
#    build: ./
#    command: python3 main_news.py
#    restart: always
#  main_f:
#    build: ./
#    command: python3 main_vedomosti.py -f
#    restart: always
#  main_s:
#    build: ./
#    command: python3 main_vedomosti.py -s
#    restart: always
#  main_t:
#    build: ./
#    command: python3 main_vedomosti.py -t
#    restart: always
#  main_a:
#    build: ./
#    command: python3 main_vedomosti.py -a
#    restart: always
  redis:
    image: redis:alpine
    restart: always
  celery:
    build: ./
    command: celery -A core worker --loglevel=INFO --concurrency=10
    restart: always
    depends_on:
      - redis
  celery-beat:
    build: ./
    command: celery -A core beat -l info
    restart: always
    depends_on:
      - redis