# Generated by Django 3.1.4 on 2021-08-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postvideo',
            old_name='photo_url',
            new_name='video_url',
        ),
    ]
